##Experiment No. 8
#Name: Anik Jain
#PRN: 25070123178
#Batch: A-3
#Title: NumPy

In [1]:
#Declaraton of Numpy
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([{1,2,3},{4,5,6}])
print(a)
print(b)

[10 20 30 40]
[{1, 2, 3} {4, 5, 6}]


In [2]:
#Dimension of array
print(a.ndim)
print(b.ndim)

1
1


In [3]:
# Find out shape of array
print(a.shape)
print(b.shape)

(4,)
(2,)


In [4]:
# Find out data type of array
print(a.dtype)
print(b.dtype)

int64
object


In [5]:
# In Built functions using numpy
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Creates symmetric matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Creates diagonal matrix
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1.5,10,10)

array([ 1.5       ,  2.44444444,  3.38888889,  4.33333333,  5.27777778,
        6.22222222,  7.16666667,  8.11111111,  9.05555556, 10.        ])

In [ ]:
a + 5

array([15, 25, 35, 45])

In [10]:
# Mean of array
np.mean(a)

np.float64(25.0)

In [8]:
# Median of array
np.median(a)

np.float64(25.0)

In [12]:
# Find maximum
np.max(a)

np.int64(40)

In [13]:
# Find minimum
np.min(a)

np.int64(10)

In [9]:
# Find sum
np.sum(a)

np.int64(100)